config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root             'static_pages#home'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'projects' => 'projects#new'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :projects, only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :description, presence: true, length: { maximum: 140 }
  validates :title, presence: true, length: { maximum: 25 }
  validates :genre_tag, presence: true, length: { maximum: 25 }
  validate  :picture_size

 private

    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :logged_in_user, only: [:create, :destroy]


  def new
      @project = current_user.projects.build if logged_in?
  end
  
  def create
  	@project = current_user.projects.build(project_params)
    if @project.save
      flash[:success] = "Project created successfully!"
      redirect_to root_url
    else
    @feed_items = []
      render 'users/show'
    end
  end

   def destroy
    @project.destroy
    flash[:success] = "Your Project Has Been Deleted"
    redirect_to request.referrer || root_url
  end

  private

    def project_params
      params.require(:project).permit(:title, :description, :genre_tag, :genre_tag2, :picture)
    end

    def correct_project
      @project = current_user.projects.find_by(id: params[:id])
      redirect_to root_url if @project.nil?
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :genre_tag %><br>
    <%= f.text_area :genre_tag %>
  </div>
  <div class="field">
    <%= f.label :genre_tag2 %><br>
    <%= f.text_area :genre_tag2 %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<li id="project-<%= project.id %>">
  <p <span class="user"><%= link_to project.user.name, project.user %></span></p>
  <p <span class="title"> <b>Project title</b> - <%= project.title %></span> </p>
  <p <span class="genre_tag"> <b> Genre </b> - <%= project.genre_tag %></span> </p>
  <p <span class="description"> <b> Project info </b> - <%= project.description %></span> </p>
  <%= image_tag project.picture.url if project.picture? %>
  <p></p>
  <span class="timestamp">
    <i> Posted <%= time_ago_in_words(project.created_at) %> ago. </i>
    <% if current_user?(project.user) %>
      <%= link_to "delete", project, method: :delete,
                                       data: { confirm: "Confirm that you wish to delete this project" } %>
    <% end %>
    <p></p>
  </span>
</li>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projects</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.content %></td>
        <td><%= project.user_id %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h2>Post a Project to 7music</h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@project, html: { multipart: true }) %>

<% if project.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(project.errors.count, "error") %>.
    </div>
    <ul>
    <% project.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
    
      <%= f.label :Project_title%>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :Project_Description%>
      <%= f.text_field :description, class: 'form-control' %>
      <p></p>
      <%= f.label :Genre_Tag%>
      <p></p>
      <%= f.select :genre_tag, options_for_select(%w[Techno House Tech-house Hip-Hop Funk Soul Acoustic])  %>
      <p></p>
      <p></p>
      <%= f.label :Second_Genre_Tag%>
      <p></p>
      <%= f.select :genre_tag2, options_for_select(%w[Techno House Tech-house Hip-Hop Funk Soul Acoustic])%>
      <p></p>
      <%= f.label :Project_picture %>
      <p></p>
       <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
      </span>
  <p></p>
      <%= f.submit "Create my project", class: "btn btn-primary" %>
<% end %>
</div>
</div>

<script type="text/javascript">
  $('#project_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @project.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @project.user_id %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>